### ISSUE TITLE
Update for GNOME 3.18

### ISSUE THREAD

**Issue by kparal** [sustmi/gnome-shell-extensions-sustmi#34]
Hello,

GNOME 3.18 has been released and many people already use it. Could you please update your WindowOverlay Icons extension at extensions.gnome.org to support this new GNOME version?

Thanks!

**Comment by sustmi** [comment]
Hello, @kparal . Done in 8af824690c1e660b99605a93d06b5e2a7fcf7099.

**Comment by kparal** [comment]
Thanks!
