### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by tjw0lf** [sustmi/gnome-shell-extensions-sustmi#39]
How do i install this manually please

**Comment by sustmi** [comment]
If you do not want to install it through your web browser on https://extensions.gnome.org, you can install it from GIT:
```bash
$ git clone https://github.com/sustmi/gnome-shell-extensions-sustmi.git
$ cp -RT gnome-shell-extensions-sustmi/windowoverlay-icons ~/.local/share/gnome-shell/extensions/windowoverlay-icons@sustmidown.centrum.cz
```
And then restart gnome shell by `ALT+F2` and running `r` command.

**Comment by tjw0lf** [comment]
what do you mean by this.

(To install historymanager-prefix-search just use the name in paths instead of windowoverlay-icons.)


Thank you i got it installed. windowoverlay-icons

**Comment by sustmi** [comment]
> what do you mean by this.
There are two extensions in this repository:
* `windowoverlay-icons` and
* `historymanager-prefix-search`

If you followed the commands, you installed `windowoverlay-icons`. If you want to manually install `historymanager-prefix-search` plugin, the second command should be:
```bash
$ cp -RT gnome-shell-extensions-sustmi/historymanager-prefix-search ~/.local/share/gnome-shell/extensions/historymanager-prefix-search@sustmidown.centrum.cz
```

**Comment by tjw0lf** [comment]
what do you mean by this.

(To install historymanager-prefix-search just use the name in paths instead of windowoverlay-icons.)

Thank you i got it installed. windowoverlay-icons

**Comment by tjw0lf** [comment]
What do you mean

historymanager-prefix-search plugin, the second command should be:

$ cp -RT gnome-shell-extensions-sustmi/historymanager-prefix-search ~/.local/share/gnome-shell/extensions/historymanager-prefix-search@sustmidown.centrum.cz

What does that do

historymanager-prefix-search plugin, I don't understand what this is for

**Comment by sustmi** [comment]
The discussion continues in https://github.com/sustmi/gnome-shell-extensions-sustmi/issues/40 .
