### ISSUE TITLE
Extension doesn't work well with native placement on startup / if enabling it before native p.

### ISSUE THREAD

**Issue by danielesegato** [sustmi/gnome-shell-extensions-sustmi#4]
Hi,

I use native windows placement which is better then the default one (in my opinion).

This extension doesn't work well with it:
* if you enable native windows placement AFTER window overlay the window overlay is gone
* on startup this always happen and I have to manually disable and re-enable the windows overlay extension

can you fix it?

Gnome 3.4

**Comment by sustmi** [comment]
Hi @danielesegato, I am closing the issue.
Native-window-placement extension does not overwrite ```_init``` and ```updatePositions``` functions any more so the extensions should be compatible.
https://github.com/GNOME/gnome-shell-extensions/blob/gnome-3-16/extensions/native-window-placement/extension.js
