### ISSUE TITLE
Clearly marking releases

### ISSUE THREAD

**Issue by terrycloth** [sustmi/gnome-shell-extensions-sustmi#46]
I'ma a package maintainer for Fedora. Some users prefer to install and update GNOME Shell extensions from the usual system package manager, because they can then manage all packages in the same workflow. I like your extensions, so I'm working on packaging them for Fedora too.

I'm not sure how to tell what the latest reasonably stable releases of your extensions are, however. The GitHub repo has not tagged a release in a few years, and the GNOME Shell Extensions website does not list extension version information anywhere, as far as I can tell. What should I be basing the package sources on?

**Comment by sustmi** [comment]
Hi @terrycloth . You can get my extensions into the Fedora repository? That would be awesome!

I would like to tag the releases according to the version numbers on extensions.gnome.org but there are two extensions in this repository and both have different versions. :/
Either I would need to split the repository or create tag versions that would be different from those on extensions.gnome.org.
What do you think?

**Comment by sustmi** [comment]
I would personally rather keep the extensions in one repository.
I admit, it was a bad choice (it was made back in the days I did not know the difference between Git and FTP) but I think moving the code could confuse people even more.

Do you have any suggestions for the version numbers I should choose? Would it be OK to start from v1 and just increment it with every new release of any of the extensions?

**Comment by terrycloth** [comment]
I don't know of any scriptable way to download the GNOME exentions website; it's not especially transparent to those sorts of queries.

From the git side, I don't know if it would be too confusing if you mentioned in the READMEs that you were going to split the repository. And I'm pretty sure there's a way to preserve file history when splitting into two separate repos.

If you prefer to keep all the code in a single repository, I can think of two options:

- you could release both extensions together under a single commit tag. The GNOME project itself does this for a lot of its software: every six months or so, they bump everything to the next even-numbered 3.XX version. However, that sort of collective versioning scheme maybe makes more sense when all the packages in the group tend to be pretty active. In your situation, tagging a single release for both would suggest that both packages need to be rebuilt, even though only one might have actually gotten any code changes.
- Another option might be to create *separate* tags that can indicate a new release for one extension at a time. It's common to name tags after the version release number with a leading "v", right. For example `v1.2.3` or whatever. In your case, you'd make tags named something like `historymanager-v1.2.3` when HistoryManager Prefix Search is ready for an update, and likewise `windowoverlay-v1.2.3` when WindowOverlay Icons is ready for an update.

**Comment by sustmi** [comment]
Ok @terrycloth, so I decided to split the repository into two separate repositories:
- https://github.com/sustmi/gnome-shell-extension-historymanager-prefix-search
- https://github.com/sustmi/gnome-shell-extension-windowoverlay-icons

The release tags will now be in sync with versions on https://extensions.gnome.org .

Thanks for making me finally do the split. :)
